[".local/share/shellstrap/fish/plugins/fzf-tab"]
type = "git-repo"
url = "https://github.com/jethrokuan/fzf"
refreshPeriod = "24h"

[".local/share/shellstrap/zsh/plugins/fzf-tab"]
type = "git-repo"
url = "https://github.com/Aloxaf/fzf-tab"
refreshPeriod = "24h"

[".local/share/shellstrap/zsh/plugins/zsh-completions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-completions"
refreshPeriod = "24h"

[".local/share/shellstrap/zsh/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting"
refreshPeriod = "24h"

[".local/share/shellstrap/zsh/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions"
refreshPeriod = "24h"
