[tools]
node = "latest"
deno = "latest"
bun = "latest"
uv = "latest"
go = "latest"
usage = "latest"
"ubi:aquaproj/aqua" = "latest"
"ubi:pkgxdev/pkgx" = "latest"
"pipx:kube-shell" = "latest"
"pipx:litecli" = "latest"
rust = "latest"
# "ubi:charmbracelet/gum" = "latest"
# "ubi:pemistahl/grex" = "latest"
# "ubi:MaybeJustJames/zephyr" = "latest"
# "ubi:google/yamlfmt" = "latest"
# "ubi:kkinnear/zprint" = "latest"
# "ubi:nektro/zigmod" = "latest"
# "ubi:joerdav/xc" = "latest"
# "ubi:vultr/vultr-cli" = "latest"
# "ubi:charmbracelet/vhs" = "latest"
# "ubi:ovh/venom" = "latest"
# "ubi:traefik/traefik" = "latest"
# "ubi:tree-sitter/tree-sitter" = "latest"
# "ubi:titan-data/titan" = "latest"
# "ubi:stefanprodan/timoni" = "latest"
# "ubi:tellerops/teller" = "latest"

[tasks.docker]
run = "docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest"

[settings]
experimental = true

[settings.pipx]
uvx = true

[settings.npm]
bun = true

