[tools]
node = "latest"
deno = "latest"
bun = "latest"
uv = "latest"
go = "latest"
usage = "2.16"
claude = "latest"
biome = "latest"
dprint = "latest"
# "npm:@openai/codex" = "latest"

[tasks.docker]
run = "docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest"
[tasks.refresh]
dir = "{{cwd}}"
run = '''
mise run stop
mise run reset
docker builder prune --filter "until=168h" -f
docker volume prune -f
mise run start
'''

[settings]
experimental = true
color_theme = "catppuccin"
idiomatic_version_file_enable_tools = []

[settings.pipx]
uvx = true

[settings.npm]
bun = true

